/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指标口径目录
         * @description 返回全部基础指标与派生指标的名称、公式与精度；与后端计算共用同一份定义。
         */
        get: operations["listMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 账号密码登录
         * @description 校验账号口令，签发短期访问令牌与刷新令牌。账号不存在、口令错误、账号停用及锁定统一返回 INVALID_CREDENTIALS。Java 业务服务按账号及来源 IP 限制失败登录，锁定期内正确口令也拒绝；成功登录或改密提交后清零账号与当前 IP 的失败计数。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新访问令牌
         * @description 用刷新令牌换取新的令牌对，旧刷新令牌随即失效；已失效的刷新令牌再次出现时吊销该账号全部刷新令牌。
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退出登录
         * @description 吊销提交的刷新令牌。访问令牌无状态，最长 15 分钟后自然失效，前端退出时应同时丢弃。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改口令
         * @description 临时口令账号也可调用。成功后吊销该账号全部刷新令牌并签发新的令牌对。
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前账号、权限与导航
         * @description 返回角色、权限、数据范围以及按权限裁剪后的导航分组。临时口令账号也可调用。
         */
        get: operations["getCurrentPrincipal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取账号界面偏好
         * @description 主题模式、主题预设与各页面列设置按账号保存，换设备后保持一致。从未保存时返回默认值且 revision 为 0。
         */
        get: operations["getPreferences"];
        /**
         * 保存账号界面偏好
         * @description 带上最后读到的 revision；期间被其他设备修改则返回 409。
         */
        put: operations["updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 筛选条可选值
         * @description 返回日期范围内、当前账号数据范围可见的媒体、产品、代理、账户与运营。
         */
        get: operations["getFilterOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 聚合查询
         * @description 按所选维度汇总；派生指标由汇总后的基础指标重算，合计行同理。结果受账号数据范围约束。
         */
        post: operations["queryAggregate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 分天明细
         * @description 在聚合维度前固定加入日期维度，便于逐日对比；与聚合共用同一筛选与口径。
         */
        post: operations["queryDaily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 趋势序列
         * @description 按天或小时输出指标序列，可按一个维度拆成最多 8 条线，其余合并为「其他」。按小时时跨度不超过 7 天。
         */
        post: operations["queryTrend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/roi-anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ROI 异常清单
         * @description 列出消耗达到门槛且 ROI 低于阈值的对象；阈值与门槛随请求传入并回显在 rule 中。
         */
        post: operations["queryRoiAnomalies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原始明细
         * @description 不做汇总的入库明细，分页返回，用于核对导入数据。
         */
        post: operations["queryRawDetail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出 CSV
         * @description 与页面使用同一查询与数据范围生成 CSV（UTF-8 带 BOM），导出结果与屏幕所见一致。原始明细导出需要真实口径权限。
         */
        post: operations["exportReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mappings/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 账户归属映射列表 */
        get: operations["listAccountMappings"];
        /**
         * 批量新增或修改映射
         * @description 逐条比对 revision；任一条版本已变化则整批不写入并返回 409。写入记审计日志。
         */
        put: operations["upsertAccountMappings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传媒体导出表
         * @description 解析后按文件覆盖的日期整天替换入库，重复上传同一天不会累加。异步处理，返回任务。
         */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询导入任务 */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 账号列表
         * @description 公司管理员看到本租户账号；代理管理员只看到本代理下的账号。
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * 创建账号
         * @description 服务端生成一次性临时口令，只在本响应返回；不能授予超出操作者自身范围的角色或数据。
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 修改角色与数据范围
         * @description 带 revision 防止覆盖他人修改；真实口径与对外口径权限不能同时授予。
         */
        put: operations["updateUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 审计日志
         * @description 按时间倒序游标分页，记录映射、导入、账号与权限等写操作的前后值。
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询助手可用状态 */
        get: operations["getAgentCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询授权范围内的虚构计划 */
        get: operations["listAgentCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本人运行记录 */
        get: operations["listAgentRuns"];
        put?: never;
        /** 提交模型任务 */
        post: operations["createAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 回读本人任务和证据 */
        get: operations["getAgentRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/runs/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认或拒绝具体沙箱变更 */
        post: operations["decideAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本人沙箱执行回执 */
        get: operations["listAgentReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountMapping */
        AccountMapping: {
            /** Account */
            account: string;
            /** Media */
            media: string;
            /** Agency */
            agency: string | null;
            /** Product */
            product: string | null;
            /** Operator */
            operator: string | null;
            /** Revision */
            revision: number;
        };
        /** AccountMappingInput */
        AccountMappingInput: {
            /** Account */
            account: string;
            /** Media */
            media: string;
            /** Agency */
            agency?: string | null;
            /** Product */
            product?: string | null;
            /** Operator */
            operator?: string | null;
            /**
             * Revision
             * @description null 表示新建；更新时须带最后读到的版本号
             */
            revision?: number | null;
        };
        /** AccountMappingPage */
        AccountMappingPage: {
            /** Items */
            items: components["schemas"]["AccountMapping"][];
            /** Total */
            total: number;
        };
        /** AccountMappingUpsert */
        AccountMappingUpsert: {
            /** Items */
            items: components["schemas"]["AccountMappingInput"][];
        };
        /** AuditEvent */
        AuditEvent: {
            /** Id */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** Target Type */
            target_type: string;
            /** Target Id */
            target_id: string;
            /**
             * Detail
             * @description 随动作而定的前后值；键名由动作决定，值可以是嵌套结构（如角色列表、数据范围）
             */
            detail: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** AuditEventPage */
        AuditEventPage: {
            /** Items */
            items: components["schemas"]["AuditEvent"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Body_createImport */
        Body_createImport: {
            /**
             * File
             * @description 媒体后台导出的 .xlsx 文件
             */
            file: string;
            /** Media */
            media: string;
        };
        /**
         * DataScope
         * @description Java 服务端授权范围；维度之间取交集。省略或 null 表示该维度不限，空数组 [] 表示该维度没有任何授权值，查询不会返回事实数据。这是授权范围，不是报表请求中用于清除筛选条件的空筛选数组。
         */
        DataScope: {
            /**
             * Agencies
             * @description 可见代理；null 或省略表示不限；[] 表示无授权值
             */
            agencies?: string[] | null;
            /**
             * Products
             * @description 可见产品；null 或省略表示不限；[] 表示无授权值
             */
            products?: string[] | null;
            /**
             * Operators
             * @description 可见运营；null 或省略表示不限；[] 表示无授权值
             */
            operators?: string[] | null;
        };
        /**
         * Error
         * @description RFC 9457 Problem Details（application/problem+json），所有 4xx/5xx 统一使用。
         */
        Error: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /**
             * Code
             * @enum {string}
             */
            code: "AUTH_REQUIRED" | "INVALID_CREDENTIALS" | "PASSWORD_CHANGE_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "VALIDATION_FAILED" | "RESULT_TOO_LARGE" | "INTERNAL_ERROR" | "NOT_IMPLEMENTED" | "HTTP_ERROR";
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** FilterOptions */
        FilterOptions: {
            /** Media */
            media: components["schemas"]["Option"][];
            /** Products */
            products: components["schemas"]["Option"][];
            /** Agencies */
            agencies: components["schemas"]["Option"][];
            /** Accounts */
            accounts: components["schemas"]["Option"][];
            /** Operators */
            operators: components["schemas"]["Option"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** ImportRowError */
        ImportRowError: {
            /** Row */
            row: number;
            /** Column */
            column: string | null;
            /** Message */
            message: string;
        };
        /** ImportTask */
        ImportTask: {
            /** Id */
            id: string;
            /** Media */
            media: string;
            /** File Name */
            file_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "succeeded" | "failed";
            /**
             * Stat Dates
             * @description 文件覆盖的日期；入库按日期整天替换，重复导入不会累加
             */
            stat_dates: string[];
            /** Rows Total */
            rows_total: number;
            /** Rows Replaced */
            rows_replaced: number;
            /** Errors */
            errors: components["schemas"]["ImportRowError"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        JsonValue: unknown;
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MetricCatalog */
        MetricCatalog: {
            /** Items */
            items: components["schemas"]["MetricDefinition"][];
        };
        /** MetricDefinition */
        MetricDefinition: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "base" | "derived";
            /**
             * Unit
             * @enum {string}
             */
            unit: "money" | "count" | "ratio" | "per_unit";
            /** Formula */
            formula: string;
            /** Description */
            description: string;
            /** Precision */
            precision: number;
        };
        /** NavGroup */
        NavGroup: {
            /** Title */
            title: string;
            /** Pages */
            pages: components["schemas"]["NavPage"][];
        };
        /** NavPage */
        NavPage: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Route */
            route: string;
        };
        /** Option */
        Option: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /**
             * New Password
             * @description 至少 10 位，不能与当前口令相同
             */
            new_password: string;
        };
        /**
         * Preferences
         * @description 账号级偏好；revision 为服务端当前版本号。
         */
        Preferences: {
            /**
             * Theme Mode
             * @enum {string}
             */
            theme_mode: "light" | "dark" | "system";
            /**
             * Theme Preset
             * @enum {string}
             */
            theme_preset: "aurora-blue" | "arc-purple" | "quantum-cyan" | "pulse-green" | "corona-gold" | "molten-orange" | "rose-wave" | "glacier-blue" | "nebula-purple" | "deep-space-gray" | "neon-cyan" | "custom";
            /**
             * Custom Primary
             * @description theme_preset 为 custom 时的主色
             */
            custom_primary?: string | null;
            /**
             * Table Columns
             * @description 按页面保存的列顺序与显隐，键为页面 id
             */
            table_columns?: {
                [key: string]: string[];
            };
            /**
             * Revision
             * @description 客户端最后读到的版本号，用于并发冲突检测
             */
            revision: number;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /**
             * Theme Mode
             * @enum {string}
             */
            theme_mode: "light" | "dark" | "system";
            /**
             * Theme Preset
             * @enum {string}
             */
            theme_preset: "aurora-blue" | "arc-purple" | "quantum-cyan" | "pulse-green" | "corona-gold" | "molten-orange" | "rose-wave" | "glacier-blue" | "nebula-purple" | "deep-space-gray" | "neon-cyan" | "custom";
            /**
             * Custom Primary
             * @description theme_preset 为 custom 时的主色
             */
            custom_primary?: string | null;
            /**
             * Table Columns
             * @description 按页面保存的列顺序与显隐，键为页面 id
             */
            table_columns?: {
                [key: string]: string[];
            };
            /**
             * Revision
             * @description 客户端最后读到的版本号，用于并发冲突检测
             */
            revision: number;
        };
        /** Principal */
        Principal: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Tenant Id */
            tenant_id: string;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: string[];
            data_scope: components["schemas"]["DataScope"];
            /** Must Change Password */
            must_change_password: boolean;
            /**
             * Visible Metrics
             * @description 当前账号可查看的指标；前端据此裁剪列选择，接口仍独立校验
             */
            visible_metrics: ("cost" | "revenue" | "impressions" | "clicks" | "launches" | "callbacks" | "conversions" | "roi" | "ctr" | "cpm" | "cpc" | "click_arpu" | "launch_rate" | "cvr" | "conversion_cost" | "callback_cost" | "launch_callback_rate" | "revenue_gap")[];
            /**
             * Navigation
             * @description 按权限裁剪后的导航；仅用于展示，接口仍独立鉴权
             */
            navigation: components["schemas"]["NavGroup"][];
        };
        /** RawDetailQuery */
        RawDetailQuery: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            filters?: components["schemas"]["ReportFilters"];
            /** Keyword */
            keyword?: string | null;
            /** Sort */
            sort?: components["schemas"]["SortSpec"][];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 100
             */
            page_size: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReportColumn */
        ReportColumn: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Kind */
            kind: "dimension" | ("base" | "derived");
            /** Unit */
            unit?: ("money" | "count" | "ratio" | "per_unit") | null;
            /** Precision */
            precision?: number | null;
        };
        /** ReportFilters */
        ReportFilters: {
            /**
             * Media
             * @description 媒体；空列表表示不限
             */
            media?: string[];
            /** Products */
            products?: string[];
            /** Agencies */
            agencies?: string[];
            /** Accounts */
            accounts?: string[];
            /** Operators */
            operators?: string[];
        };
        /** ReportQuery */
        ReportQuery: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            filters?: components["schemas"]["ReportFilters"];
            /**
             * Keyword
             * @description 在维度值中搜索
             */
            keyword?: string | null;
            /** Group By */
            group_by?: ("stat_date" | "stat_hour" | "media" | "product" | "agency" | "account" | "operator" | "campaign")[];
            /**
             * Metrics
             * @description null 表示默认指标列；对外口径账号请求收益类指标返回 403
             */
            metrics?: ("cost" | "revenue" | "impressions" | "clicks" | "launches" | "callbacks" | "conversions" | "roi" | "ctr" | "cpm" | "cpc" | "click_arpu" | "launch_rate" | "cvr" | "conversion_cost" | "callback_cost" | "launch_callback_rate" | "revenue_gap")[] | null;
            /** Sort */
            sort?: components["schemas"]["SortSpec"][];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
        };
        /** ReportResult */
        ReportResult: {
            /** Columns */
            columns: components["schemas"]["ReportColumn"][];
            /** Rows */
            rows: {
                [key: string]: string | number | null;
            }[];
            /**
             * Totals
             * @description 当前筛选范围的合计，派生指标由合计基础指标重算
             */
            totals: {
                [key: string]: string | number | null;
            };
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Rows */
            total_rows: number;
            /** Data As Of */
            data_as_of: string | null;
        };
        /** RoiAnomaly */
        RoiAnomaly: {
            /** Dimensions */
            dimensions: {
                [key: string]: string;
            };
            /** Cost */
            cost: number;
            /** Revenue */
            revenue: number;
            /** Roi */
            roi: number | null;
            /** Reason */
            reason: string;
        };
        /** RoiAnomalyQuery */
        RoiAnomalyQuery: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            filters?: components["schemas"]["ReportFilters"];
            /** Group By */
            group_by?: ("stat_date" | "stat_hour" | "media" | "product" | "agency" | "account" | "operator" | "campaign")[];
            /**
             * Roi Below
             * @description ROI 低于该值视为异常
             * @default 1.1
             */
            roi_below: number;
            /**
             * Min Cost
             * @description 消耗低于该值不参与判断，避免小额噪声
             * @default 200
             */
            min_cost: number;
        };
        /** RoiAnomalyResult */
        RoiAnomalyResult: {
            /** Rule */
            rule: string;
            /** Items */
            items: components["schemas"]["RoiAnomaly"][];
            /** Data As Of */
            data_as_of: string | null;
        };
        /** SortSpec */
        SortSpec: {
            /**
             * Field
             * @description 列 key，维度或指标
             */
            field: string;
            /**
             * Direction
             * @default desc
             * @enum {string}
             */
            direction: "asc" | "desc";
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description 访问令牌有效秒数
             */
            expires_in: number;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Bucket */
            bucket: string;
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /** TrendQuery */
        TrendQuery: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            filters?: components["schemas"]["ReportFilters"];
            /**
             * Granularity
             * @default day
             * @enum {string}
             */
            granularity: "day" | "hour";
            /** Metrics */
            metrics?: ("cost" | "revenue" | "impressions" | "clicks" | "launches" | "callbacks" | "conversions" | "roi" | "ctr" | "cpm" | "cpc" | "click_arpu" | "launch_rate" | "cvr" | "conversion_cost" | "callback_cost" | "launch_callback_rate" | "revenue_gap")[];
            /**
             * Split By
             * @description 按该维度拆成多条序列
             */
            split_by?: ("stat_date" | "stat_hour" | "media" | "product" | "agency" | "account" | "operator" | "campaign") | null;
        };
        /** TrendResult */
        TrendResult: {
            /** Metrics */
            metrics: ("cost" | "revenue" | "impressions" | "clicks" | "launches" | "callbacks" | "conversions" | "roi" | "ctr" | "cpm" | "cpc" | "click_arpu" | "launch_rate" | "cvr" | "conversion_cost" | "callback_cost" | "launch_callback_rate" | "revenue_gap")[];
            /** Series */
            series: components["schemas"]["TrendSeries"][];
            /** Data As Of */
            data_as_of: string | null;
        };
        /** TrendSeries */
        TrendSeries: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** UpsertResult */
        UpsertResult: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Unchanged */
            unchanged: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: ("super_admin" | "company_admin" | "operator" | "agency_admin" | "customer" | "readonly")[];
            data_scope?: components["schemas"]["DataScope"];
        };
        /** UserCreated */
        UserCreated: {
            user: components["schemas"]["UserSummary"];
            /**
             * One Time Password
             * @description 仅在本响应返回一次；首次登录必须修改
             */
            one_time_password: string;
            /**
             * Must Change Password
             * @default true
             * @constant
             */
            must_change_password: true;
        };
        /** UserPage */
        UserPage: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
            /** Total */
            total: number;
        };
        /** UserRolesUpdate */
        UserRolesUpdate: {
            /** Roles */
            roles: ("super_admin" | "company_admin" | "operator" | "agency_admin" | "customer" | "readonly")[];
            data_scope: components["schemas"]["DataScope"];
            /** Revision */
            revision: number;
        };
        /** UserSummary */
        UserSummary: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: ("super_admin" | "company_admin" | "operator" | "agency_admin" | "customer" | "readonly")[];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            data_scope: components["schemas"]["DataScope"];
            /** Revision */
            revision: number;
        };
        /** AgentSubmit */
        AgentSubmit: {
            /** Prompt */
            prompt: string;
            /** Request Id */
            request_id: string;
            /**
             * Context
             * @default null
             */
            context: {
                [key: string]: unknown;
            } | null;
        };
        /** AgentDecision */
        AgentDecision: {
            /** Approve */
            approve: boolean;
            /** Request Id */
            request_id: string;
            /** Proposal Id */
            proposal_id: string;
        };
        /** AgentCapabilities */
        AgentCapabilities: {
            /** Available */
            available: boolean;
            /** Model */
            model: string | null;
            /** Unavailable Reason */
            unavailable_reason: string | null;
            /** Can Execute */
            can_execute: boolean;
            /** Execution Mode */
            execution_mode: string;
            /** Max Steps */
            max_steps: number;
        };
        /** AgentCampaign */
        AgentCampaign: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Media */
            media: string;
            /** Account */
            account: string;
            /** Campaign */
            campaign: string;
            /** Agency */
            agency: string | null;
            /** Product */
            product: string | null;
            /** Operator */
            operator: string | null;
            /** Bid */
            bid: number;
            /** Daily Budget */
            daily_budget: number;
            /** Revision */
            revision: number;
            /** Execution Mode */
            execution_mode: string;
        };
        /** AgentCampaignList */
        AgentCampaignList: {
            /** Items */
            items: components["schemas"]["AgentCampaign"][];
        };
        /** AgentAmounts */
        AgentAmounts: {
            /** Bid */
            bid: number;
            /** Daily Budget */
            daily_budget: number;
        };
        /** AgentAppliedChange */
        AgentAppliedChange: {
            /** Campaign Id */
            campaign_id: string;
            /** Campaign Name */
            campaign_name: string;
            /** Account */
            account: string;
            /** Revision */
            revision: number;
            before: components["schemas"]["AgentAmounts"];
            after: components["schemas"]["AgentAmounts"];
            /** New Revision */
            new_revision: number;
        };
        /** AgentChange */
        AgentChange: {
            /** Campaign Id */
            campaign_id: string;
            /** Campaign Name */
            campaign_name: string;
            /** Account */
            account: string;
            /** Revision */
            revision: number;
            before: components["schemas"]["AgentAmounts"];
            after: components["schemas"]["AgentAmounts"];
        };
        /** AgentEvent */
        AgentEvent: {
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: unknown;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentProposal */
        AgentProposal: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Changes */
            changes: components["schemas"]["AgentChange"][];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** AgentReceipt */
        AgentReceipt: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Proposal Id */
            proposal_id: string;
            /** Execution Mode */
            execution_mode: string;
            /** Status */
            status: string;
            /** Changes */
            changes: components["schemas"]["AgentAppliedChange"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRun */
        AgentRun: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_confirmation" | "succeeded" | "rejected" | "failed";
            /** Answer */
            answer: string | null;
            /** Error */
            error: string | null;
            /** Events */
            events: components["schemas"]["AgentEvent"][];
            proposal: components["schemas"]["AgentProposal"] | null;
            receipt: components["schemas"]["AgentReceipt"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** AgentRunList */
        AgentRunList: {
            /** Items */
            items: components["schemas"]["AgentRun"][];
        };
        /** AgentReceiptList */
        AgentReceiptList: {
            /** Items */
            items: components["schemas"]["AgentReceipt"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务可用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指标目录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricCatalog"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已换发 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description 已修改 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentPrincipal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前账号 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前偏好 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 版本已变化，请刷新后重试 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getFilterOptions: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可选值 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptions"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryAggregate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportQuery"];
            };
        };
        responses: {
            /** @description 聚合结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryDaily: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportQuery"];
            };
        };
        responses: {
            /** @description 分天结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryTrend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrendQuery"];
            };
        };
        responses: {
            /** @description 趋势序列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryRoiAnomalies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoiAnomalyQuery"];
            };
        };
        responses: {
            /** @description 异常清单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoiAnomalyResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryRawDetail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawDetailQuery"];
            };
        };
        responses: {
            /** @description 明细分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query: {
                /** @description 导出哪个视图 */
                view: "aggregate" | "daily" | "raw";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportQuery"];
            };
        };
        responses: {
            /** @description CSV 文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAccountMappings: {
        parameters: {
            query?: {
                media?: string | null;
                keyword?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 映射分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountMappingPage"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    upsertAccountMappings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountMappingUpsert"];
            };
        };
        responses: {
            /** @description 写入结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertResult"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 版本已变化，请刷新后重试 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_createImport"];
            };
        };
        responses: {
            /** @description 已受理 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportTask"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 上传文件超过大小限制 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportTask"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                keyword?: string | null;
                status?: ("active" | "disabled") | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 账号分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreated"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 版本已变化，请刷新后重试 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateUserRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRolesUpdate"];
            };
        };
        responses: {
            /** @description 已修改 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 对象不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 版本已变化，请刷新后重试 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                action?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description 未登录或令牌已失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限，或超出账号的数据范围 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求参数校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAgentCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCapabilities"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgentCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCampaignList"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgentRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunList"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSubmit"];
            };
        };
        responses: {
            /** @description 成功 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDecision"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgentReceipts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentReceiptList"];
                };
            };
            /** @description 登录失效 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 无权限或授权已变化 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 目标不可见 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 请求、状态、版本冲突或任务容量已满 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 输入校验失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description 模型接口尚未配置 */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
