-- 基线：第 2 阶段由 Alembic 建出的表结构，逐字转写自当时数据库的 schema dump。
-- 已经在跑的库不会重跑这一版（baseline-on-migrate），新库从这里开始建。
-- 自 V2 起表结构由本目录负责，Alembic 不再新增修订。

create table tenants (
    id         varchar(32)  not null,
    name       varchar(64)  not null,
    created_at timestamptz  not null default now(),
    constraint pk_tenants primary key (id)
);

create table users (
    id                   varchar(32) not null,
    tenant_id            varchar(32) not null,
    username             varchar(32) not null,
    display_name         varchar(32) not null,
    password_hash        text        not null,
    status               varchar(16) not null default 'active',
    must_change_password boolean     not null default false,
    data_scope           jsonb       not null default '{}'::jsonb,
    revision             integer     not null default 1,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now(),
    constraint pk_users primary key (id),
    constraint uq_users_username unique (username),
    constraint ck_users_ck_users_status check (status in ('active', 'disabled')),
    constraint fk_users_tenant_id_tenants foreign key (tenant_id) references tenants (id)
);

create table user_roles (
    user_id varchar(32) not null,
    role    varchar(32) not null,
    constraint pk_user_roles primary key (user_id, role),
    constraint ck_user_roles_ck_user_roles_role check (
        role in ('super_admin', 'company_admin', 'operator', 'agency_admin', 'customer', 'readonly')),
    constraint fk_user_roles_user_id_users foreign key (user_id) references users (id) on delete cascade
);

create table refresh_tokens (
    id         bigint      not null generated by default as identity,
    user_id    varchar(32) not null,
    token_hash varchar(64) not null,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    constraint pk_refresh_tokens primary key (id),
    constraint uq_refresh_tokens_token_hash unique (token_hash),
    constraint fk_refresh_tokens_user_id_users foreign key (user_id) references users (id) on delete cascade
);

create index ix_refresh_tokens_user_id on refresh_tokens (user_id);

create table user_preferences (
    user_id        varchar(32) not null,
    theme_mode     varchar(16) not null,
    theme_preset   varchar(32) not null,
    custom_primary varchar(7),
    table_columns  jsonb       not null default '{}'::jsonb,
    revision       integer     not null,
    updated_at     timestamptz not null default now(),
    constraint pk_user_preferences primary key (user_id),
    constraint fk_user_preferences_user_id_users foreign key (user_id) references users (id) on delete cascade
);

create table account_mappings (
    tenant_id  varchar(32) not null,
    media      varchar(32) not null,
    account    varchar(64) not null,
    agency     varchar(64),
    product    varchar(64),
    operator   varchar(64),
    revision   integer     not null default 1,
    updated_at timestamptz not null default now(),
    constraint pk_account_mappings primary key (tenant_id, media, account),
    constraint fk_account_mappings_tenant_id_tenants foreign key (tenant_id) references tenants (id)
);

-- 投放明细事实。产品 / 代理 / 运营不落在这里，查询时经账户映射补齐，映射修改对历史生效。
create table ad_facts (
    id          bigint        not null generated by default as identity,
    tenant_id   varchar(32)   not null,
    stat_date   date          not null,
    stat_hour   smallint,
    media       varchar(32)   not null,
    account     varchar(64)   not null,
    campaign    varchar(64),
    cost        numeric(14,2) not null default 0,
    revenue     numeric(14,2) not null default 0,
    impressions bigint        not null default 0,
    clicks      bigint        not null default 0,
    launches    bigint        not null default 0,
    callbacks   bigint        not null default 0,
    conversions bigint        not null default 0,
    loaded_at   timestamptz   not null default now(),
    constraint pk_ad_facts primary key (id),
    constraint ck_ad_facts_ck_ad_facts_stat_hour check (stat_hour is null or (stat_hour between 0 and 23)),
    constraint fk_ad_facts_tenant_id_tenants foreign key (tenant_id) references tenants (id)
);

create index ix_ad_facts_tenant_id_stat_date on ad_facts (tenant_id, stat_date);
create index ix_ad_facts_tenant_id_media_account on ad_facts (tenant_id, media, account, stat_date);
