import {
  Ban, Bell, BookOpen, CalendarClock, CalendarDays, CloudDownload, Factory, FileText, Handshake,
  LayoutDashboard, Link2, Megaphone, Package, Percent, PieChart, Receipt, RefreshCcw, ScrollText, Send,
  ShieldAlert, Shuffle, Sigma, SlidersHorizontal, Table, Tag, TrendingUp, TriangleAlert, UsersRound,
  Users, Wallet, PanelsTopLeft, type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  workspace: PanelsTopLeft,
  home: LayoutDashboard,
  products: Package,
  categories: Tag,
  "media-accounts": Wallet,
  ingest: CloudDownload,
  "field-mappings": Shuffle,
  campaigns: Megaphone,
  "campaigns-today": CalendarClock,
  "report-aggregate": Sigma,
  "report-daily": CalendarDays,
  "raw-detail": Table,
  "report-trend": TrendingUp,
  "roi-anomalies": TriangleAlert,
  "vendor-report": Factory,
  "sub-platform": PieChart,
  "blocklist-stats": ShieldAlert,
  "media-report": FileText,
  "media-stats": PieChart,
  "source-packages": Package,
  "audience-packages": UsersRound,
  compensation: Handshake,
  "agency-cost": Handshake,
  conversions: Send,
  callbacks: RefreshCcw,
  "convert-rules": SlidersHorizontal,
  blocklist: Ban,
  alerts: Bell,
  rebates: Percent,
  settlements: Receipt,
  "user-manage": Users,
  "mapping-manage": Link2,
  "metric-catalog": BookOpen,
  "audit-log": ScrollText,
};
